version: "3"
networks:
  dbwebb:
services:
  test:
    image: microblog:test
    hostname: microblog-test
    volumes:
      - ./:/home/microblog/app
  prod:
    networks:
      dbwebb:
    image: turingcop/microblog:1.0.0-prod
    hostname: microblog
    ports:
      - 8000:5000
    links:
      - mysql:mysql
    environment:
      DATABASE_URL: mysql+pymysql://microblog:password@mysql/microblog
  mysql:
    networks:
      dbwebb:
    image: mysql/mysql-server:5.7
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "password"