# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY requirements requirements
COPY boot_test.sh ./

RUN  <<-EOF
    apk add --no-cache make=4.3-r0
    python -m venv .venv
    .venv/bin/pip3 install -r requirements/test.txt
EOF

ENV FLASK_APP microblog.py

RUN <<-EOF
    chmod +x boot_test.sh
    chown -R microblog:microblog ./
EOF

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot_test.sh"]