- name: Start database container
  docker_container:
    name: mysql
    image: mysql/mysql-server:5.7
    volumes:
      - /data:/var/lib/mysql
    ports: 3306:3306
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "password"
