---
-   import_playbook: gather_vm_instances.yml
-   import_playbook: terminate_instances.yml
-   import_playbook: provision_instances.yml
-   import_playbook: gather_vm_instances.yml
-   import_playbook: 10-first-minutes.yml
-   import_playbook: deploy_database.yml
-   import_playbook: deploy_microblog.yml
-   import_playbook: deploy_lb.yml
