# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dockerhub_push:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login
    uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push
    uses: docker/build-push-action@v3
      with:
        file: ./docker/Dockerfile_prod
        push: true